version: "3.9"
services:
  web:
    build: .
    # command: ls
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7153"
      - "7154"
    volumes:
      - ./Inmobiliaria:/app
    depends_on:
        - db
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"