version: "3.9"
services:
  web:
    build: ./app
    # command: ls
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7153:7153"
      - "7154:7154"
    volumes:
      - ./app:/app
#     depends_on:
#         - db
#   db:
#     image: "mcr.microsoft.com/mssql/server"
#     environment:
#         SA_PASSWORD: "Your_password123"
#         ACCEPT_EULA: "Y"
#         TRUSTED_CONNECTION: "TRUE"
#     ports:
#       - "1434:1433"
#     volumes:
#       - sqlserver-data:/var/opt/mssql

# volumes:
#   sqlserver-data:
